### ISSUE TITLE
Subclassed content show both items in the item list after save and wont allow deletion.

### ISSUE THREAD

**Issue by sjdines** [django-fluent/django-fluent-contents#58]
If you have the setup:

```
class A(ContentItem):
    <fields here>

class B(A):
    <fields here>
```

When you save an instance of item B in a region then it will show populated values for A and B.

It will also not allow deletion of the content item as it will have the suffix `a_ptr` instead of `contentitem_ptr` which is required by `get_formset_dom_info` and the line `id_field: $("#" + field_prefix + "-contentitem_ptr"),`.

I have two fixes which could be applied here:

Change the line `id_field: $("#" + field_prefix + "-contentitem_ptr"),` to `id_field: $("[id^=" + field_prefix + "-][id$=_ptr]")` which would allow deletion.

Also in the function `cp_data.init` after `$fs_items` are calculated perform some cleaning up:

```
cp_data.init = function()
  {
    // Find all formset items.
    var $all_items   = $(".inline-contentitem-group > .inline-related");
    var $empty_items = $all_items.filter(".empty-form");
    var $fs_items    = $all_items.filter(":not(.empty-form)");
    var $fs_non_content_items = $fs_items.filter(":not(:has([id$=contentitem_ptr]))");

    for (var i = 0; i < $fs_non_content_items.length; i++) {
      var item = $fs_non_content_items.eq(i);
      var itm_name = item.find('input[id$=_ptr]').attr('id').replace('id_' + item.attr('id') + '-', '').replace('_ptr', '');
      var related_items = $fs_items.filter('[id^=' + itm_name + ']');

      for(var j = 0; j < related_items.length; j++) {
        if(
          item.children('input').attr('value') == related_items.eq(j).children('input').attr('value') &&
          item.find('.cp-formset-item-fields > [id$=placeholder]').attr('value') == related_items.eq(j).find('.cp-formset-item-fields > [id$=placeholder]').attr('value') &&
          item.find('.cp-formset-item-fields > [id$=sort_order]').attr('value') == related_items.eq(j).find('.cp-formset-item-fields > [id$=sort_order]').attr('value')
        ) {
          $fs_items = $fs_items.not('#' + related_items.eq(j).attr('id'));
          break;
        }
      }
    }

    // Group all formset items by the placeholder they belong to.
    // This administration is used as quick lookup, to avoid unneeded DOM querying.
    if( cp_data.placeholders )
.
.
.
```

Which remove the duplicate content items list.

I would like to get thoughts on this approach? Is this something of interest or not too bother? If it is I can clean up my code a little before submitting a pull request.

**Comment by vdboor** [comment]
If you a proper pull request for the `_ptr` cleanup, I'll merge it.

I do wonder what you're trying to do here. Inheriting from `ContentItem` is not an issue, as the markup plugin also does that. However, when you show both the base class and it's derived class in the list, you're doing pretty weird things that can't be supported. Yes, the item would appear twice, but after all, that's what you're doing explicitly by adding both.

**Comment by heldinz** [comment]
I'm encountering the same issue where I have a couple of custom classes that inherit from `ContentItem` and another custom class that inherits from `OEmbedItem` (`CaptionedOEmbedItem`). I'm unable to delete any `CaptionedOEmbedItem`s because their ID fields end in `-oembeditem_ptr` instead of `-contentitem_ptr`.

Is there anything strange about what I'm doing or is this something that should be fixed? I wondered if I should be subclassing `AbstractOEmbedItem` instead of `OEmbedItem` but when I do that, I'm unable to save any of these items. The page appears to save successfully but the embed items disappear on reload.
