### ISSUE TITLE
Animate moving content items up and down

### ISSUE THREAD

**Issue by cogat** [django-fluent/django-fluent-contents#82]
Content items look visually similar to each other, and so when you click the up or down arrows the instant change can be disorienting. This can be addressed by animating the move.

**Comment by vdboor** [comment]
The commit is merged and improved! Thanks for the work, this was a great inspiration to achieve the effect. I had no idea it could be that "simple" to achieve the swap effect! 😃 The code is now improved to work with more "advanced" (read TinyMCE/WYSIWYG) plugins too.
