### ISSUE TITLE
How to use this on the predefined model ?

### ISSUE THREAD

**Issue by guganselvaraj** [django-fluent/django-fluent-contents#87]
I want to view a "doc" file in the browser, which is already been stored in the document model in my custom django application. How to do this using django-fluent-contents ? Im a fresher to django ! i followed all the steps that are given but somehow not able to get it ! please throw some light on this !?

**Comment by vdboor** [comment]
You can create a plugin that holds a `ForeignKey` to the model in your Django project.
Something like this:

```
class DocumentItem(ContentItem):
    document = models.ForeignKey(Document)
```
