### ISSUE TITLE
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by adrielwerlich** [django-fluent/django-fluent-contents#99]
Hello there I´m following the steps to install the django fluent but as soon as I execute migrate he gives error message

RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

also is saying that 'django.contrib.comments' is deprecated

**Comment by vdboor** [comment]
Hi! This is fixed by adding `django.contrib.sites` to your `INSTALLED_APPS`.
The `django.contrib.comments` can be replaced with `django_comments` (`pip install django-contrib-comments`)
